name: Tests

on:
  push:
    branches:
     - master
  pull_request_target:
  workflow_dispatch:

jobs:   
  test:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
      - run: npm i
      - run: npm test
